//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Model
{
    using GUI.ViewMD;
    using System;
    using System.Collections.Generic;

    public partial class Account : ViewModelBase
    {
        public int id { get; set; }
        //public string UserName { get; set; }
        //public string DisplayName { get; set; }
        public string Avatar { get; set; }
        //public string PassWord { get; set; }
        //public int idType { get; set; }
        public int Xoa { get; set; }

        private string _UserName;
        public string UserName { get => _UserName; set { _UserName = value; OnPropertyChanged(); } }
        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private string _PassWord;
        public string PassWord { get => _PassWord; set { _PassWord = value; OnPropertyChanged(); } }
        private int _idType;
        public int idType { get => _idType; set { _idType = value; OnPropertyChanged(); } }

        public virtual TypeAcc TypeAcc { get; set; }
    }
}
