//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Model
{
    using GUI.ViewMD;
    using System;
    using System.Collections.Generic;
    
    public partial class Input : ViewModelBase
    {
        public int id { get; set; }
        //public int idCategory { get; set; }
        //public int idProduct { get; set; }
        //public System.DateTime Date_Input { get; set; }
        //public int count { get; set; }
        //public double priceInput { get; set; }

        private int _idCategory;
        public int idCategory { get => _idCategory; set { _idCategory = value; OnPropertyChanged(); } }
        private int _idProduct;
        public int idProduct { get => _idProduct; set { _idProduct = value; OnPropertyChanged(); } }
        private int _count;
        public int count { get => _count; set { _count = value; OnPropertyChanged(); } }
        private double _priceInput;
        public double priceInput { get => _priceInput; set { _priceInput = value; OnPropertyChanged(); } }
        private DateTime _Date_Input;
        public DateTime Date_Input { get => _Date_Input; set { _Date_Input = value; OnPropertyChanged(); } }


        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Product Product { get; set; }
    }
}
