//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Model
{
    using GUI.ViewMD;
    using System;
    using System.Collections.Generic;
    
    public partial class Product:ViewModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BillInfoes = new HashSet<BillInfo>();
            this.Inputs = new HashSet<Input>();
        }
    
        public int id { get; set; }
        //public string name { get; set; }
        //public int idCategory { get; set; }
        //public double price { get; set; }
        public string url { get; set; }
        public int discount { get; set; }
        public int Xoa { get; set; }

        private string _name;
        public string name { get => _name; set { _name = value; OnPropertyChanged(); } }
        private int _idCategory;
        public int idCategory { get => _idCategory; set { _idCategory = value; OnPropertyChanged(); } }
        private double _price;
        public double price { get => _price; set { _price = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input> Inputs { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
